### ISSUE TITLE
Setup Guide

### ISSUE THREAD

**Issue by mihcox** [cristianchelu/dispenser-schedule-card#5]
I was able to get this package installed, it shows up under resources tab on dashboards, but I do not see it on my home screen. Any change you could help guide me into getting this setup?

**Comment by mihcox** [comment]
![image](https://github.com/user-attachments/assets/4f7f3a34-8562-431a-a6b2-de8cea6d0d12)

**Comment by cristianchelu** [comment]
There is no entity in your HA installation with the name `sensor.feeder_raw_feed_plan`, which is what the `Entity not available` warning is about. Same for the switch, and I assume for the actions as well.

Double check your actual `Entity ID`s and replace as needed.

**Comment by mihcox** [comment]
resolved, thanks for the clarification!
